### ISSUE TITLE
Flask global blueprint folder not found.

### ISSUE THREAD

**Issue by ptrdvds** [kakulukia/pypugjs#7] opened 2018-01-29 11:11 UTC
* pypugjs version: 5.3.0
* Django version: NA
* Python version: 6.4.3
* Flask version: 12.2
* Jinja2 version: 2.10
* Operating System: OSX 10.13.3 ,Ubuntu 16.10.3 LTS and python:alpine latest

### Description

After upgrade of pypugjs to version 5.3.0 (5.x.x version) i get the following error:
**raise Exception("Include path doesn't exists")**
I use blueprints in my application and the global template folder is not found anymore resulting in the above error.
The flask project code has not changed, only the pypugjs module has changed.
I expected the upgrade to 5.3.0 to be painless but as changed to a problem because downgrade to 4.2.2 is not available anymore due to the abscence of 4.x.x verisons in PyPi.

Stacktrace here : https://gist.github.com/16b86f7bf7d7217c2986919e507a346b

**Comment by kakulukia** [comment] 2018-01-29 11:25
Like i said in the readme i cant really support all the other usage alternatives, because im not actively using anything other than the Django loader for compiling pug templates. but you could provide an actual real worl example for a basic flask/blueprints app that could be tested. 
There is this old example app, but i bet it wasnt really touched in a long time.

You coud fork this repo, jump back to the 4.2.2 tag and create that new example and create a PR with it. I will try to fix it afterwards for the current version.

I just saw there is no real tag, but use the commit from 26.4.2017 "version bump". He forgot to tag it.

**Comment by kakulukia** [comment] 2018-01-29 14:19
I just tested the old Flask example manually and enhanced it with a mixin include. Its working.
Like i said above please add a small blueprints example, so i can help you here. I cannot reproduce this with plain Flask and currently have no insights at all as to whats different in those blueprints of yours.

**Comment by kakulukia** [comment] 2018-01-29 23:35
@ptrdvds please respond

**Comment by ptrdvds** [comment] 2018-01-30 10:55
@kakulukia 
I am trying to find out why pypugjs does not work as it did with version 4.2.2 and with pyjade.
Simplyfing my flask application to the bare minimum with pypugjs and blueprints, works.
My suspicion is that there are modules in my application that do not play well together with pypugjs anymore.
Since flask is not the main target for pypugjs, i do not really know how to proceed.
I need to reevaluate what template engine i need to use, i am losing a lot of time at the moment.

**Comment by kakulukia** [comment] 2018-01-30 11:03
If its possible for you to give me access to you project, i could  try to see whats broken.

**Comment by ptrdvds** [comment] 2018-01-30 14:27
I will see if i can package the application so that it can be used outside the environments i use.
The application is a microservices app using docker, if it's components are not in place, the frontend that uses pypugjs is more or less useless.
I have tested my frontend with pypugjs 4.2.2 just to make sure and that version works as expected.

**Comment by kakulukia** [comment] 2018-02-06 14:53
Any news?

**Comment by KittenHero** [comment] 2018-02-13 14:18
That's strange: looks like release 4.2.2 didn't have even the function `visitInclude`  in `pypugjs/ext/jinja.py` (which is used by Flask) so I don't even know how it worked in the first place

**Comment by kakulukia** [comment] 2018-02-13 14:20
yes, weird indeed!

**Comment by kakulukia** [comment] 2018-02-20 10:18
Okay since the bug is confirmed to not happening with a default setup im closing the ticket since there is no update for the last 14 days. 
If you still wish to get some help with your project code @ptrdvds .. write something.

**Closed by kakulukia** 2018-02-20 10:18 UTC

**Comment by ptrdvds** [comment] 2018-02-26 13:16
Hei,
I haven't been working on this project lately, but will try to debug the problem ASAP.
Thanks for your effort.
Cheers Peter
