### ISSUE TITLE
how to call super() as in Jinja2 ?

### ISSUE THREAD

**Issue by gotexis** [kakulukia/pypugjs#45] opened 2019-02-13 07:47 UTC
#{ super() }

doesn't work..

**Comment by kakulukia** [comment] 2019-02-13 08:01
i dont recognise that syntax .. please explain, how you did setup your environment and how you are using pypugjs

**Comment by gotexis** [comment] 2019-02-13 10:13
Haha thanks for the prompt response.

I believe in jinja2 we need to call { super() } to include the parent block's content.


After digging into the pug documentations, I figured the correct syntax is ' block extend  '

**Comment by kakulukia** [comment] 2019-02-13 10:17
so the issue is resolved?

**Comment by gotexis** [comment] 2019-02-14 05:24
Yes!

**Comment by kakulukia** [comment] 2019-02-15 00:26
Then you should close it.

**Closed by kakulukia** 2019-02-15 00:26 UTC
